language: python

python:
  - "3.5"

install:
  - pip install discord.py
  - pip install sqlalchemy
  - pip install psycopg2

script:
  - python -m compileall ./bot.py
  - python -m compileall ./cogs
  - python -m compileall ./setup.py
